'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''

list = [1,2]

while True:
    new_number = list[-1] + list[-2]
    list.append(new_number)
    if list[-1] > 4000000:
        list.pop(-1)
        break

sum = 0
for i in list:
    if i%2 != 0: continue
    sum += i

print(sum)
